export const actionTypes = {
  SIGNUP_USER: "SIGNUP_USER",
  LOGIN_USER: "LOGIN_USER",
  SIGNOUT_USER: "SIGNOUT_USER",
  MAKE_REQUEST: "MAKE_REQUEST",
  CREATE_DRAFT_PIN: "CREATE_DRAFT_PIN",
  SAVE_DRAFT_AS_PIN: "SAVE_DRAFT_AS_PIN",
  UPDATE_DRAFT_LOCATION: "UPDATE_DRAFT_LOCATION",
  SET_CURRENT_PIN: "SET_CURRENT_PIN",
  UNSELECT_CURRENT_PIN: "UNSELECT_CURRENT_PIN",

  DISCARD_DRAFT: "DISCARD_DRAFT",
  DELETE_PIN: "DELETE_PIN",
  GET_PINS: "GET_PINS",

  UPDATE_CURRENT_PIN: "UPDATE_CURRENT_PIN",
  SAVE_CURRENT_PIN: "SAVE_CURRENT_PIN",
  DISCARD_CURRENT_PIN_CHANGES: "DISCARD_CURRENT_PIN_CHANGES",
  SHOW_COMMENTS: "SHOW_COMMENTS",
  HIDE_COMMENTS: "HIDE_COMMENTS",
  GET_COMMENTS: "GET_COMMENTS",
  CREATE_COMMENT: "CREATE_COMMENT",
  ON_PIN_ADDED: "ON_PIN_ADDED",
  ON_PIN_DELETED: "ON_PIN_DELETED",
  ON_PIN_UPDATED: "ON_PIN_UPDATED",
  ON_COMMENT_ADDED: "ON_COMMENT_ADDED",
  ADDING_MODE:"ADDING_MODE"
};
