export const actionTypes = {
  SIGNUP_USER: "SIGNUP_USER",
  LOGIN_USER: "LOGIN_USER",
  SIGNOUT_USER: "SIGNOUT_USER",
  MAKE_REQUEST: "MAKE_REQUEST",

  CREATE_DRAFT_PIN: "CREATE_DRAFT_PIN",
  UPDATE_DRAFT_LOCATION: "UPDATE_DRAFT_LOCATION",

  SAVE_DRAFT_AS_PIN: "SAVE_DRAFT_AS_PIN",

  SET_CURRENT_PIN: "SET_CURRENT_PIN",
  UNSELECT_CURRENT_PIN: "UNSELECT_CURRENT_PIN",

  DISCARD_DRAFT: "DISCARD_DRAFT",
  DELETE_PIN: "DELETE_PIN",
  GET_SIGHTINGS: "GET_SIGHTINGS",

  UPDATE_CURRENT_PIN: "UPDATE_CURRENT_PIN",
  SAVE_CURRENT_PIN: "SAVE_CURRENT_PIN",
  DISCARD_CURRENT_PIN_CHANGES: "DISCARD_CURRENT_PIN_CHANGES",
  SHOW_COMMENTS: "SHOW_COMMENTS",
  HIDE_COMMENTS: "HIDE_COMMENTS",
  GET_COMMENTS: "GET_COMMENTS",
  CREATE_COMMENT: "CREATE_COMMENT",
  ON_SIGHTING_ADDED: "ON_SIGHTING_ADDED",
  ON_PIN_DELETED: "ON_PIN_DELETED",
  ON_PIN_UPDATED: "ON_PIN_UPDATED",
  ON_COMMENT_ADDED: "ON_COMMENT_ADDED",
  // ADDING_MODE: "ADDING_MODE",

  FILTER_OPEN: "OPEN_FILTER",
  FILTER_CLOSE: "CLOSE_FILTER",
  FILTER_MARINE_MAMMAL_TYPE: "FILTER_MARINE_MAMMAL_TYPE",
  FILTER_DATE: "SET_DATE_FILTER",

  SHOW_NAV_SIDE: "SHOW_NAV_SIDE",
  HIDE_NAV_SIDE: "HIDE_NAV_SIDE",

  UPDATE_VIEWPORT: "UPDATE_VIEWPORT",
  START_BUSY: "START_BUSY",
  END_BUSY: "END_BUSY",
  DRAFT_SAVED_SUCCESSFULLY: "DRAFT_SAVED_SUCCESSFULLY"
};
