export const actionTypes = {
  SIGNUP_USER: "SIGNUP_USER",
  LOGIN_USER: "LOGIN_USER",
  SIGNOUT_USER: "SIGNOUT_USER",

  UPDATE_VIEWPORT: "UPDATE_VIEWPORT",

  GET_SIGHTINGS: "GET_SIGHTINGS",

  CREATE_DRAFT_PIN: "CREATE_DRAFT_PIN",
  UPDATE_DRAFT_LOCATION: "UPDATE_DRAFT_LOCATION",
  DRAFT_SAVED_SUCCESSFULLY: "DRAFT_SAVED_SUCCESSFULLY",
  ON_SIGHTING_ADDED: "ON_SIGHTING_ADDED",
  DISCARD_DRAFT: "DISCARD_DRAFT",

  SHOW_COMMENTS: "SHOW_COMMENTS",
  HIDE_COMMENTS: "HIDE_COMMENTS",
  GET_COMMENTS: "GET_COMMENTS",
  CREATE_COMMENT: "CREATE_COMMENT",

  FILTER_OPEN: "OPEN_FILTER",
  FILTER_CLOSE: "CLOSE_FILTER",
  FILTER_MARINE_MAMMAL_TYPE: "FILTER_MARINE_MAMMAL_TYPE",
  FILTER_DATE: "SET_DATE_FILTER",

  SHOW_NAV_SIDE: "SHOW_NAV_SIDE",
  HIDE_NAV_SIDE: "HIDE_NAV_SIDE",

  START_BUSY: "START_BUSY",
  END_BUSY: "END_BUSY",
  SET_ERROR: "SET_ERROR",
  SET_POPUP: "SET_POPUP",

  TOGGLE_FULLSCREEN_PHOTO: "TOGGLE_FULLSCREEN_PHOTO",
  SHOW_SIGHTING: "SHOW_SIGHTING",
  CLOSE_SIGHTING: "CLOSE_SIGHTING"
};
